[versions]

# Fabric Properties
# Get new versions at https://fabricmc.net/develop and https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.20.4"
quilt_mappings = "1.20.4+build.2"
parchment_mappings = "2023.10.22"
fabric_loader = "0.15.3"

# Dependencies
fabric_api = "0.91.2+1.20.4"
kotlin = "1.9.22"
fabric_kotlin = "1.10.17+kotlin.1.9.22"
frozenLib = "1.5.2-mc1.20.4"

# External Mods
clothConfig = "13.0.114"
modMenu = "9.0.0-pre.1"
terraBlender = "1.20.2-3.2.0.14"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
parchmentMappings = { module = "org.parchmentmc.data:parchment-1.20.2", version.ref = "parchment_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc:fabric-api", version.ref = "fabric_api" }
fabric_kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric_kotlin" }
frozenLib = { module = "maven.modrinth:frozenlib", version.ref = "frozenLib" }

clothConfig = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "clothConfig" }
modMenu = { module = "com.terraformersmc:modmenu", version.ref = "modMenu" }
terraBlender = { module = "com.github.glitchfiend:TerraBlender-fabric", version.ref = "terraBlender" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
fabric_loom = { id = "fabric-loom", version = "+" }
quilt_licenser = { id = "org.quiltmc.gradle.licenser", version = "+" }
grgit = { id = "org.ajoberstar.grgit", version = "+" }
minotaur = { id = "com.modrinth.minotaur", version = "+" }
